[book]
authors = ["Daniel Knopik"]
language = "en"
multilingual = false
src = "src"
title = "ethshadow Guide"

[output.html]
git-repository-url = "https://github.com/dknopik/ethereum-shadow"
edit-url-template = "https://github.com/dknopik/ethereum-shadow/edit/main/guide/{path}"
